-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.admins
(
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.cities
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(80) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.cv_cover_letters
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cv_id integer NOT NULL,
    content text NOT NULL,
    created_at date,
    is_active boolean,
    is_deleted boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.cv_edu_infos
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    university_id integer NOT NULL,
    university_department_id integer NOT NULL,
    cv_id integer NOT NULL,
    starting_date date NOT NULL,
    graduation_date date,
    created_at date,
    is_active boolean,
    is_deleted boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.cv_foreign_languages
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cv_id integer NOT NULL,
    language_level_id integer NOT NULL,
    foreign_language_id integer NOT NULL,
    created_at date,
    is_active boolean,
    is_deleted boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.cv_social_media
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    social_media_id integer NOT NULL,
    cv_id integer NOT NULL,
    link character varying(200),
    created_at date,
    is_active boolean,
    is_deleted boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.cv_technologies
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cv_id integer NOT NULL,
    technology_id integer NOT NULL,
    created_at date,
    is_active boolean,
    is_deleted boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.cv_work_experiences
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cv_id integer NOT NULL,
    job_position_id integer NOT NULL,
    company_name character varying(200),
    starting_date date NOT NULL,
    ending_date date,
    created_at date,
    is_active boolean,
    is_deleted boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.cvs
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    job_seeker_id integer NOT NULL,
    created_at date,
    is_active boolean,
    is_deleted boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers
(
    user_id integer NOT NULL,
    website character varying(250) NOT NULL,
    phone_number character varying(30) NOT NULL,
    is_verified boolean NOT NULL,
    company_name character varying(250) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public."employers_verification_byAdmins"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employer_id integer NOT NULL,
    admin_id integer NOT NULL,
    created_at date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.foreign_languages
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    foreign_language_name character varying(100),
    created_at date,
    is_active boolean,
    is_deleted boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_adverts
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    job_position_id integer NOT NULL,
    city_id integer NOT NULL,
    employer_id integer NOT NULL,
    description text NOT NULL,
    open_position_count integer NOT NULL,
    deadline date NOT NULL,
    salary_min integer,
    salary_max integer,
    advert_status boolean,
    created_at date NOT NULL,
    is_active boolean,
    is_deleted boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_positions
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    job_title character varying(150) NOT NULL,
    created_at date,
    is_active boolean,
    is_deleted boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.jobseekers
(
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    national_id character varying(11) NOT NULL,
    is_verified boolean NOT NULL,
    date_of_birth date NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.language_levels
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    level_name character varying(30),
    created_at date,
    is_active boolean,
    is_deleted boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.photos
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cv_id integer NOT NULL,
    photo_url character varying(100),
    created_at date,
    is_active boolean,
    is_deleted boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.social_media
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    social_media_name character varying(100) NOT NULL,
    created_at date,
    is_active boolean,
    is_deleted boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.technologies
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    tecnology_name character varying(150) NOT NULL,
    created_at date,
    is_active boolean,
    is_deleted boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.universities
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    university_name character varying(150) NOT NULL,
    created_at date,
    is_active boolean,
    is_deleted boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.university_departments
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    university_id integer NOT NULL,
    university_department_name character varying(150),
    created_at date,
    is_active boolean,
    is_deleted boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(100) NOT NULL,
    password character varying(30) NOT NULL,
    created_at date,
    is_active boolean,
    is_deleted boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.verification_codes
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    code character varying(50) NOT NULL,
    is_confirmed boolean NOT NULL,
    created_at date,
    activation_date date,
    PRIMARY KEY (id)
);

ALTER TABLE public.admins
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.cv_cover_letters
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (id)
    NOT VALID;


ALTER TABLE public.cv_edu_infos
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (id)
    NOT VALID;


ALTER TABLE public.cv_edu_infos
    ADD FOREIGN KEY (university_department_id)
    REFERENCES public.university_departments (id)
    NOT VALID;


ALTER TABLE public.cv_edu_infos
    ADD FOREIGN KEY (university_id)
    REFERENCES public.universities (id)
    NOT VALID;


ALTER TABLE public.cv_foreign_languages
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (id)
    NOT VALID;


ALTER TABLE public.cv_foreign_languages
    ADD FOREIGN KEY (foreign_language_id)
    REFERENCES public.foreign_languages (id)
    NOT VALID;


ALTER TABLE public.cv_foreign_languages
    ADD FOREIGN KEY (language_level_id)
    REFERENCES public.language_levels (id)
    NOT VALID;


ALTER TABLE public.cv_social_media
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (id)
    NOT VALID;


ALTER TABLE public.cv_social_media
    ADD FOREIGN KEY (social_media_id)
    REFERENCES public.social_media (id)
    NOT VALID;


ALTER TABLE public.cv_technologies
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (id)
    NOT VALID;


ALTER TABLE public.cv_technologies
    ADD FOREIGN KEY (technology_id)
    REFERENCES public.technologies (id)
    NOT VALID;


ALTER TABLE public.cv_work_experiences
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (id)
    NOT VALID;


ALTER TABLE public.cv_work_experiences
    ADD FOREIGN KEY (job_position_id)
    REFERENCES public.job_positions (id)
    NOT VALID;


ALTER TABLE public.cvs
    ADD FOREIGN KEY (job_seeker_id)
    REFERENCES public.jobseekers (user_id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public."employers_verification_byAdmins"
    ADD FOREIGN KEY (admin_id)
    REFERENCES public.admins (user_id)
    NOT VALID;


ALTER TABLE public."employers_verification_byAdmins"
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (user_id)
    NOT VALID;


ALTER TABLE public.job_adverts
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (id)
    NOT VALID;


ALTER TABLE public.job_adverts
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (user_id)
    NOT VALID;


ALTER TABLE public.job_adverts
    ADD FOREIGN KEY (job_position_id)
    REFERENCES public.job_positions (id)
    NOT VALID;


ALTER TABLE public.jobseekers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.photos
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (id)
    NOT VALID;


ALTER TABLE public.university_departments
    ADD FOREIGN KEY (university_id)
    REFERENCES public.universities (id)
    NOT VALID;


ALTER TABLE public.verification_codes
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;

END;